name: Run Python Script Daily

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_call:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      TUYA_CLIENT_ID: ${{ secrets.TUYA_CLIENT_ID }}
      TUYA_SECRET_KEY: ${{ secrets.TUYA_SECRET_KEY }}
      GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
      DEVICES: ${{ secrets.DEVICES }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        run: python main.py
